/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D BODEGAS VILLAELENA.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano001.geometry}
        material={materials["Material.001"]}
        position={[0.5, 0.21, 0.23]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002.geometry}
        material={materials["Material.001"]}
        position={[0.46, 0.21, 0.11]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano003.geometry}
        material={materials["Material.001"]}
        position={[0.66, 0.16, -0.07]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto.geometry}
        material={materials["Material.001"]}
        position={[0.77, 0, 0.12]}
        rotation={[Math.PI / 2, 0, -0.32]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto001.geometry}
        material={materials["Material.001"]}
        position={[0.63, 0.07, 0.49]}
        rotation={[Math.PI / 2, 0, -0.32]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto002.geometry}
        material={materials["Material.001"]}
        position={[0.71, 0.05, -0.06]}
        rotation={[Math.PI / 2, 0, -0.32]}
        scale={0.5}
      />
      <group position={[0.32, 0, 0.1]} rotation={[Math.PI / 2, 0, 2.82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom"].geometry}
          material={materials.tq_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_1"].geometry}
          material={materials.tq_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom_2"].geometry}
          material={materials.tq_ARD_edge}
        />
      </group>
      <group position={[-0.05, 0, 0.31]} rotation={[Math.PI / 2, 0, 2.82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom001"].geometry}
          material={materials["tq_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom001_1"].geometry}
          material={materials["back-dil"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq_ARD-geom001_2"].geometry}
          material={materials["tq_ARD_edge.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D BODEGAS VILLAELENA.gltf");
